name: realx
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=2.1.0
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - anyio=4.10.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.5
  - async-timeout=5.0.1
  - attrs=25.4.0
  - babel=2.16.0
  - beautifulsoup4=4.13.5
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cachetools=4.2.2
  - certifi=2026.01.04
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - comm=0.2.1
  - contourpy=1.2.0
  - cpuonly=2.0
  - cryptography=46.0.2
  - cudatoolkit=11.8.0
  - cudnn=8.9.2.26
  - cupti=11.8.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - fftw=3.3.9
  - filelock=3.20.0
  - flatbuffers=25.2.10
  - fontconfig=2.14.1
  - fonttools=4.60.1
  - freetype=2.13.3
  - frozenlist=1.8.0
  - fsspec=2025.12.0
  - giflib=5.2.2
  - glib=2.84.4
  - glib-tools=2.84.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-auth=1.28.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpc-cpp=1.46.1
  - grpcio=1.42.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.16.0
  - h5py=3.12.1
  - hdf5=1.12.1
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=58.2
  - idna=3.11
  - intel-openmp=2023.0.0
  - ipykernel=6.30.1
  - ipython=8.30.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - json5=0.9.25
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.7
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.2.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.84.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.20
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - magma=2.7.1
  - markdown=3.8
  - markupsafe=3.0.2
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mistune=3.1.2
  - mkl=2023.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.7.0
  - mysql=5.7.24
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook-shim=0.2.4
  - numexpr=2.8.7
  - numpy=1.22.3
  - numpy-base=1.22.3
  - oauthlib=3.3.1
  - openjpeg=2.5.4
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - overrides=7.4.0
  - packaging=25.0
  - pandas=2.0.3
  - pandocfilters=1.5.1
  - parso=0.8.4
  - pcre2=10.46
  - pexpect=4.9.0
  - pillow=11.1.0
  - pip=25.2
  - platformdirs=4.3.7
  - ply=3.11
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycares=4.10.0
  - pycparser=2.23
  - pygments=2.19.1
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-flatbuffers=24.3.25
  - python-json-logger=3.2.1
  - python-tzdata=2025.2
  - pytorch=2.3.0
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.3
  - referencing=0.30.2
  - requests=2.32.5
  - requests-oauthlib=2.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - rsa=4.7.2
  - scikit-learn=1.7.2
  - scipy=1.12.0
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=80.9.0
  - sip=6.7.12
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.50.2
  - stack_data=0.6.3
  - sympy=1.14.0
  - tbb=2021.8.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - termcolor=2.1.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - torchtriton=2.3.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - uvloop=0.22.1
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - gast==0.4.0
      - keras==2.10.0
      - libclang==18.1.1
      - protobuf==3.19.6
      - tabulate==0.9.0
      - tensorboard==2.10.1
      - tensorflow==2.10.0
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tqdm==4.67.1
      - xlrd==2.0.2
