name: l2x2018
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.2.25
  - certifi=2021.5.30
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=21.2.2
  - pthread-stubs=0.3
  - python=3.6.13
  - readline=8.2
  - setuptools=58.0.4
  - sqlite=3.50.2
  - tk=8.6.14
  - wheel=0.37.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - astor==0.8.1
      - async-generator==1.10
      - attrs==22.2.0
      - babel==2.11.0
      - backcall==0.2.0
      - beautifulsoup4==4.6.3
      - bleach==4.1.0
      - cached-property==1.5.2
      - cffi==1.15.1
      - charset-normalizer==2.0.12
      - contextvars==2.4
      - cycler==0.11.0
      - dataclasses==0.8
      - debugpy==1.5.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - entrypoints==0.4
      - fsspec==2022.1.0
      - gast==0.6.0
      - geographiclib==1.52
      - geopy==1.20.0
      - grpcio==1.48.2
      - h5py==2.10.0
      - idna==3.10
      - immutables==0.19
      - importlib-metadata==4.8.3
      - importlib-resources==5.4.0
      - ipykernel==5.5.6
      - ipython==7.16.3
      - ipython-genutils==0.2.0
      - jedi==0.17.2
      - jinja2==3.0.3
      - joblib==1.1.1
      - json5==0.9.16
      - jsonschema==3.2.0
      - jupyter-client==7.1.2
      - jupyter-core==4.9.2
      - jupyter-server==1.13.1
      - jupyterlab==3.2.9
      - jupyterlab-pygments==0.1.2
      - jupyterlab-server==2.10.3
      - keras==2.2.4
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2
      - kiwisolver==1.3.1
      - markdown==3.3.7
      - markupsafe==2.0.1
      - matplotlib==2.2.5
      - mistune==0.8.4
      - nbclassic==0.3.5
      - nbclient==0.5.9
      - nbconvert==6.0.7
      - nbformat==5.1.3
      - nest-asyncio==1.6.0
      - nltk==3.3
      - notebook==6.4.10
      - numpy==1.14.0
      - packaging==21.3
      - pandas==0.23.4
      - pandocfilters==1.5.1
      - parso==0.7.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==8.4.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.36
      - protobuf==3.19.6
      - ptyprocess==0.7.0
      - pycparser==2.21
      - pygments==2.14.0
      - pyparsing==3.1.4
      - pyrsistent==0.18.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - requests==2.27.1
      - scikit-learn==0.24.2
      - scipy==1.4.1
      - seaborn==0.9.1
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.2.0
      - tensorboard==1.12.2
      - tensorflow==1.12.0
      - termcolor==1.1.0
      - terminado==0.12.1
      - testpath==0.6.0
      - threadpoolctl==3.1.0
      - tornado==6.1
      - tqdm==4.64.1
      - traitlets==4.3.3
      - typing-extensions==4.1.1
      - urllib3==1.26.20
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websocket-client==1.3.1
      - werkzeug==2.0.3
      - zipp==3.6.0
